name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.10']

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
#     - name: Run Tests
#       run: |
#         python manage.py makemigrations LegacySite
#         python manage.py makemigrations
#         python manage.py migrate
#         sh import_dbs.sh
    - name: check for bugs
      working-directory: ./LegacySite
      run: python manage.py shell -c "from . import tests"
        

        
        
        
